//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class TrackPage {
    
    /// <summary>
    /// VideoPageCode1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_VideoPageCode VideoPageCode1;
    
    /// <summary>
    /// RadioPlayerGuest1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_RadioPlayerGuest RadioPlayerGuest1;
    
    /// <summary>
    /// VideoPageCodeB1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_VideoPageCodeB VideoPageCodeB1;
    
    /// <summary>
    /// ExtraContent11 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ExtraContent1 ExtraContent11;
    
    /// <summary>
    /// VideoPageCodeC1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::UserControls_VideoPageCodeC VideoPageCodeC1;
}
